!function(e,t){for(var r in t)e[r]=t[r]}(exports,function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=10)}([function(e,t){e.exports=require("apollo-client")},function(e,t){e.exports=require("apollo-link-http")},function(e,t){e.exports=require("apollo-link-context")},function(e,t){e.exports=require("apollo-cache-inmemory")},function(e,t){e.exports=require("graphql-tag")},function(e,t){e.exports=require("node-fetch")},,,,,function(e,t,r){const{ApolloClient:n}=r(0),{HttpLink:o}=r(1),{setContext:i}=r(2),{InMemoryCache:a}=r(3),u=r(4),c={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"},l=new o({uri:"https://xyabwrrxxk.execute-api.us-east-1.amazonaws.com/stage",fetch:r(5)}),s=new n({link:i((e,{headers:t})=>({headers:{"x-api-key":"mX63Tp1jp4M3ExJyHutMqn3D7W9aN28lsJxWlV50"}})).concat(l),cache:new a});t.handler=((e,t,r)=>{s.query({query:u`
        {
	    shows(id:"5fc56a73-7bc9-4db6-a4d8-cfed94144047"){
		data{
			attributes{
				promoTitle
				promoDescription
				description
				shortDescription
				name
				showColor
			}
				relationships{
					media{
						data{
							attributes{
								usage
							}
							relationships{
								image {
									data{
										attributes{
											path
										}
									}
								}
								video{
									data{
										attributes{
											runTime
											episodeNumber
											title
										}
									}
								}
							}
						}
					}
				}
            }
        }
    }
    `}).then(function(e){r(null,{statusCode:200,headers:c,body:JSON.stringify(e)})}).catch(function(e){console.log(e)})})}]));